### ISSUE TITLE
আসসালামু আলাইকুম

### ISSUE THREAD

**Issue by theFahmid** [smwrhasan/site-try#1]
আমার ইস্যুটা হলো - আপনি আমাকে ছাড়া ওয়েব ডেভেলপার হয়ে যাচ্ছেন, যা মেনে নেওয়া যায় না।

**Comment by smwrhasan** [comment]
ভাই আমি তো চার দিকে ঘুরেই চলে যাচ্ছি ,ভিতরে ঢুকি নাই :)
